# Generated by Django 2.2 on 2021-01-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('addon_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, unique=True)),
                ('cost', models.FloatField()),
                ('gst', models.FloatField()),
                ('material', models.SmallIntegerField(choices=[(0, 'Gold'), (1, 'Silvers')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('cost', models.FloatField()),
                ('gst', models.FloatField(blank=True, null=True)),
                ('material', models.SmallIntegerField(choices=[(0, 'Gold'), (1, 'Silvers')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.FloatField()),
                ('gst', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_date', models.DateTimeField(default=None, null=True)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estimation.User')),
                ('items', models.ManyToManyField(related_name='orders', to='Estimation.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimation.AddOn')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estimation.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='addons',
            field=models.ManyToManyField(related_name='items', through='Estimation.ItemAddon', to='Estimation.AddOn'),
        ),
    ]
