# Generated by Django 2.2 on 2021-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaddon',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
